apiVersion: v1
kind: Service
metadata:
  name: pushgateway
  namespace: default
  labels:
    app: pushgateway
spec:
  type: NodePort
  ports:
    - port: 9091
      nodePort: 30091
  selector:
    app: pushgateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pushgateway
  labels:
    app: pushgateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pushgateway
  template:
    metadata:
      labels:
        app: pushgateway
    spec:
      containers:
        - name: pushgateway
          image: prom/pushgateway:v1.4.3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9091
