apiVersion: v1
kind: Service
metadata:
  name: kafka-ui
  namespace: default
  labels:
    app: kafka-ui
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30100
  selector:
    app: kafka-ui
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui
  labels:
    app: kafka-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-ui
  template:
    metadata:
      labels:
        app: kafka-ui
    spec:
      containers:
        - name: kafka-ui
          image: provectuslabs/kafka-ui:f98c26e4fae6b64cf97ed6061d685f08c021b17e
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: KAFKA_CLUSTERS_0_NAME
              value: kafka153
            - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
              value: "192.168.120.153:9092"
            - name: KAFKA_CLUSTERS_0_JMXPORT
              value: "29999"
            - name: KAFKA_CLUSTERS_0_KAFKACONNECT_0_USERNAME
              value: admin
            - name: KAFKA_CLUSTERS_0_KAFKACONNECT_0_PASSWORD
              value: "admin-2019"
